name: Backend workflow..

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and tag of docker image
        run: |
          docker build -t ${{ secrets.DOCKER_UNAME }}/app-server:${GITHUB_SHA::7} .

      - name: Test newly created build image
        run: docker run --rm -d --name back-cnt -p 4000:4000 ${{ secrets.DOCKER_UNAME }}/app-server:${GITHUB_SHA::7}

      - name: Push image to DockerHub
        if  : success()
        run : |
          docker login -u ${{ secrets.DOCKER_UNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_UNAME }}/app-server:${GITHUB_SHA::7}

  Change-image-tag-and-deploy:
    needs: Image-build-push
    runs-on: self-hosted

    steps:
      - name: Create docker container
        run: |
          if ! docker ps -a --format '{{.Names}}' | grep -q 'back-cnt'; then
            docker run --rm -d --name back-cnt --network host ${{ secrets.DOCKER_UNAME }}/app-server:${GITHUB_SHA::7}
          else
            echo "Container with name 'back-cnt' already exists!"
            docker stop back-cnt
            docker run --rm -d --name back-cnt --network host ${{ secrets.DOCKER_UNAME }}/app-server:${GITHUB_SHA::7}
          fi 
        
      
